# Generated by Django 5.0.6 on 2024-07-21 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.basemodel')),
                ('category_name', models.CharField(default='unknown', max_length=100)),
                ('category_slug', models.SlugField(blank=True, null=True, unique=True)),
                ('category_image', models.ImageField(upload_to='categories')),
            ],
            bases=('base.basemodel',),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.basemodel')),
                ('product_name', models.CharField(default='unknown', max_length=50)),
                ('product_slug', models.SlugField(blank=True, null=True, unique=True)),
                ('price', models.FloatField(default=True)),
                ('description', models.TextField()),
                ('category_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category')),
            ],
            bases=('base.basemodel',),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.basemodel')),
                ('product_image', models.ImageField(upload_to='products')),
                ('product_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_different_images', to='products.product')),
            ],
            bases=('base.basemodel',),
        ),
    ]
