# Generated by Django 5.0.6 on 2024-07-22 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorVariant',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.basemodel')),
                ('color', models.CharField(default='unknown', max_length=50)),
                ('product_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_color', to='products.product')),
            ],
            bases=('base.basemodel',),
        ),
        migrations.CreateModel(
            name='SizeVariant',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.basemodel')),
                ('size', models.CharField(default='unknown', max_length=50)),
                ('product_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_size', to='products.product')),
            ],
            bases=('base.basemodel',),
        ),
    ]
