# Generated by Django 5.0.6 on 2024-07-23 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_colorvariant_sizevariant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='colorvariant',
            old_name='color',
            new_name='color_name',
        ),
        migrations.RemoveField(
            model_name='colorvariant',
            name='product_instance',
        ),
        migrations.RemoveField(
            model_name='sizevariant',
            name='product_instance',
        ),
        migrations.AddField(
            model_name='colorvariant',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='color_variant',
            field=models.ManyToManyField(to='products.colorvariant'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_variant',
            field=models.ManyToManyField(to='products.sizevariant'),
        ),
        migrations.AddField(
            model_name='sizevariant',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
