# Generated by Django 5.0.6 on 2024-07-24 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        ('products', '0003_rename_color_colorvariant_color_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupan',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.basemodel')),
                ('coupan_code', models.CharField(max_length=6)),
                ('is_expire', models.BooleanField(default=False)),
                ('discount_percent', models.IntegerField(default=5)),
                ('minimum_amount', models.IntegerField(default=100)),
            ],
            bases=('base.basemodel',),
        ),
    ]
