# Generated by Django 5.0.6 on 2024-07-24 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_coupan'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupan',
            name='expiry_date',
            field=models.DateField(default='2024-07-24'),
            preserve_default=False,
        ),
    ]
